### ISSUE TITLE
Pointless if in `access-strategy-types/not.js`

### ISSUE THREAD

**Issue by adwydman** [sealcode/sealious#276]
Here's a part of the checker function for `not.js`:
```javascript
checker_function: function(context, params, item){
		var strategies;
		if (strategies instanceof Array){
			strategies = params.map((declaration) => new Sealious.AccessStrategy(declaration));
		} else {
			strategies = [new Sealious.AccessStrategy(params)];
		}
```

This conditionals don't make much sense, because `strategies` will never be an instance of Array object. Please see into it.

**Comment by kuba-orlik** [comment]
Oh, you're right, it's pointless - must've kept it there by an accident.

**Comment by adwydman** [comment]
If you find time please fix this and close the issue. :)
