### ISSUE TITLE
`is_proper_declaration` is not a function

### ISSUE THREAD

**Issue by adwydman** [sealcode/sealious#279]
There's a test in `field-type.test.js`:

```javascript
it("should use default .is_proper_declaration", function(done){
				var return_value = test_field_type.is_proper_declaration({});
				if (typeof return_value != "boolean" || return_value != true) {
					done(but_it_didnt);
				} else {
					done();
				}
			});
```

`is_proper_declaration` method definition is nowhere to be found in the project.

**Comment by kuba-orlik** [comment]
It was used for field_type_reference to check whether declared in params allowed resource_types exist

**Comment by adwydman** [comment]
Should it be still existing?

**Comment by kuba-orlik** [comment]
Well, currently it has been cleared out during one of the refactors. I think that it should definitely be existing, and `single_reference` should be using it.
